spring:
  application:
    name: chapter1
  datasource:
    url: jdbc:mysql://localhost:3306/tobi?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234